name: miga

dependencies:
  # General-purpose
  - r-base
  - r-vegan
  - r-ape
  - conda-forge::ruby
  - sqlite
  - openjdk
  - pip
  - numpy
  - pigz

  # Read processing
  - faqcs
  - falco
  - seqtk
  - fastp
  - spades

  # Assembly processing
  - hmmer
  - pyhmmer
  - bedtools
  - prodigal
  - pyrodigal
  - barrnap
  - trnascan-se
  - krona

  # Distances
  - blast
  - mcl
  - diamond
  - fastani

channels:
  - conda-forge
  - bioconda
  - anaconda
  - r
