#!/usr/bin/env ruby
#
# @package MiGA
# @author Luis M. Rodriguez-R <lmrodriguezr at gmail dot com>
# @license artistic license 2.0
# @update Jun-08-2015
#

$:.push File.expand_path(File.dirname(__FILE__) + "/lib")

require 'miga'

execs = Dir[File.expand_path(File.dirname(__FILE__) + "/bin/*")].map{ |b| File.basename b }
if %w{-v --version}.include? ARGV[0]
   puts MiGA::MiGA.VERSION
elsif %w{-V --long-version}.include? ARGV[0]
   puts MiGA::MiGA.LONG_VERSION
elsif %w{-C --citation}.include? ARGV[0]
   puts MiGA::MiGA.CITATION
elsif execs.include? ARGV[0]
   task = ARGV.shift
   load File.expand_path(File.dirname(__FILE__) + "/bin/" + task)
else
   print <<HELP.gsub /^ {3}/,""
   Microbial Genomes Atlas.

   Usage: #{$0} {action} [options]

   actions:
       #{execs.join(" ")}

   generic options:
       -h, --help		Display this screen.
       -v, --version	Show MiGA version.
       -V, --long-version	Show complete MiGA version.
       -C, --citation		How to cite MiGA.
HELP
end

